baseURL = "https://yaong-cmd.github.io/paper-blog/"
languageCode = "ko-KR"
defaultContentLanguage = "ko"
title = "일상의 소리"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

pagination.pagerSize = 10

[minify]
  disableXML = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardLineBreaks = true

[params]
  env = "production"
  description = "종이 같은 질감의 블로그."
  author = "왕밤라떼"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  DateFormat = "2006.01.02"

[params.homeInfoParams]
  Title = "일상의 소리"
  Content = "![](/images/cover.jpg)"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/shared-cmyk1"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
